"""Standalone random generation.

These helpers expose the sampling layer on its own, decoupled from trials and
statistics.  Use them when you only want reproducible random inputs -- to feed
your own computation, or to inspect the raw draws.

Reproducibility matches the engine: chunk ``i`` of ``sample_chunks(seed=s)`` is
generated by the same independent stream the simulation would use, so
``sample(inputs, n, seed=s)`` equals the single chunk of a run with the same
seed and ``chunk_size >= n``.
"""

from __future__ import annotations

from collections.abc import Iterator

import numpy as np
import polars as pl
from numpy.typing import NDArray

from .distributions import Distribution
from .rng import spawn_generators

__all__ = ["sample_arrays", "sample", "sample_chunks"]

InputsSpec = dict[str, Distribution]


def sample_arrays(
    inputs: InputsSpec,
    n: int,
    rng: np.random.Generator,
) -> dict[str, NDArray[np.generic]]:
    """Draw ``n`` samples per input into a dict of NumPy arrays (lowest level)."""
    if n < 0:
        raise ValueError(f"n must be >= 0, got {n}.")
    return {name: dist.sample(rng, n) for name, dist in inputs.items()}


def sample(inputs: InputsSpec, n: int, *, seed: int = 0) -> pl.DataFrame:
    """Draw ``n`` reproducible samples per input into a single DataFrame."""
    if n < 1:
        raise ValueError(f"n must be >= 1, got {n}.")
    if not inputs:
        raise ValueError("inputs must contain at least one distribution.")
    rng = spawn_generators(seed, 1)[0]
    return pl.DataFrame(sample_arrays(inputs, n, rng))


def sample_chunks(
    inputs: InputsSpec,
    n: int,
    *,
    chunk_size: int,
    seed: int = 0,
) -> Iterator[pl.DataFrame]:
    """Yield reproducible, memory-bounded chunks of samples.

    Each chunk uses its own independent, pre-seeded generator, so the full
    stream is reproducible regardless of ``chunk_size``.
    """
    if n < 1:
        raise ValueError(f"n must be >= 1, got {n}.")
    if chunk_size < 1:
        raise ValueError(f"chunk_size must be >= 1, got {chunk_size}.")
    if not inputs:
        raise ValueError("inputs must contain at least one distribution.")

    from .chunking import chunk_sizes  # local import to avoid an import cycle

    sizes = chunk_sizes(n, chunk_size)
    generators = spawn_generators(seed, len(sizes))
    for size, rng in zip(sizes, generators):
        yield pl.DataFrame(sample_arrays(inputs, size, rng))
